### ISSUE TITLE
Support for AJAX Quick Checkout 

### ISSUE THREAD

**Issue by packeta-user** [Zasilkovna/opencart3#23]
https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=15580

**Comment by hamrak** [comment]
Dobry den, je tato issue este aktualna? :)

**Comment by MatyasKoval** [comment]
> Dobry den, je tato issue este aktualna? ![:)](https://static-cdn.jtvnw.net/emoticons/v2/1/default/light/1.0)

Dobrý den,
tato issue je stále aktuální. 
Podporu pro tento košík do budoucna stále plánujeme, nicméně v případě, že byste se rozhodl tuto funkcionalitu implementovat, budeme velice rádi za pull request.

S přáním krásného dne,
Matyáš Kovaľ - Technická podpora Zásilkovna

**Comment by hamrak** [comment]
https://github.com/Zasilkovna/opencart3/pull/36

**Comment by MatyasKoval** [comment]
> #36

@hamrak 
Velice děkuji za PR.

S přáním krásného dne,
Matyáš Kovaľ - Technická podpora Zásilkovna

**Comment by MatyasKoval** [comment]
Dobrý den @hamrak,
Ještě jednou děkuji za Váš PR.

Nainstalovali  jsme ho a ozkoušeli jeho funkčnost a bohužel jsme narazili na chování, kdy nefunguje správně tlačítko pro výběr výdejního místa za pomocí widgetu v pokladně. 

![image](https://user-images.githubusercontent.com/92293068/164166651-3f122efb-431b-476b-a035-c1a963fc9f02.png)

Toto jsme vyzkoušeli jak na aktuální verzi AJAX košíku stažené skrze Dreamventions rozhraní, tak na AJAX košíku přímo z GitHub - v obou případech tlačítko nefungovalo.

Jedná se o vcelku podstatnou chybu - bez ní nelze podat objednávku s dopravou skrze Zásilkovnu na výdejní místo.

S přáním krásného dne,
Matyáš Kovaľ - Technická podpora Zásilkovna

**Comment by hamrak** [comment]
A ste si isty, ze ste si stiahli aj posledny zmeny, ktore som vykonal? Napr. https://github.com/Zasilkovna/opencart3/pull/36/commits/abad2f842ee95dbc2dfd3667c8624f3d6552f863 

Tam generujem prave html namiesto textu cez jquery metodu .html().

**Comment by MatyasKoval** [comment]
Dobrý den @hamrak, 
PR jsme stáhnuli aktuální a jen pro upřesnění, testovali jsem Váš PR jak na aktuální verzi (7.5.2) AJAX Quick Checkout nainstalovaném skrze Dreamventions rozhraní přímo v OC3 administraci, v tom případě se zobrazí situace výše zmíněná.

Testování jsme prováděli i přímo na verzi z GitHub Dreamventions, na který jste uvedl odkaz v PR (7.3.4), v této verzi se tlačítko pro výběr výdejního místa widgetem zobrazí, nicméně při kliknutí na něj se nic neděje- nelze vybrat výdejní místo.

Pro upřesnění, pro kterou verzi OPC jste vyvíjel PR? 

Pokud byste preferoval, můžeme konverzaci ohledně této issue dořešit přímo přes náš email technicka.podpora@zasilkovna.cz nebo přes telefon.

S přáním krásného dne,
Matyáš Kovaľ - Technická Podpora Zásilkovna

**Comment by MatyasKoval** [comment]
Dobrý den @hamrak,
tento issue zavírám - abychom mohli uvažovat o zahrnutí PR pro košík Ajax Quick Checkout do našeho modulu, musel by fungovat s nejnovější verzí tohoto košíku. 
Pokud v budoucnu budete upravovat PR, aby fungoval i v tomto případě, tak tento issue klidně znovuotevřete.
Děkuji.

S přáním krásného dne,
Matyáš Kovaľ - Technická Podpora Zásilkovna
