### ISSUE TITLE
Desetinná čísla pro váhové limity

### ISSUE THREAD

**Issue by dandys71** [Zasilkovna/opencart3#3]
Dobrý den,

bylo by možné aby minimální a maximální váhu šlo zadávat v desetinném tvaru? Prodáváme drobné zboží a přes Zásilkovnu pouze do 5 kg. Bohužel se občas stane, že váhově se objednávka do 5 kg vejde, avšak fyzicky se díky balení limit překoná. Proto potřebujeme zadat desetinné číslo pro potřeby rezervy. 

Momentálně jsem si v DB změnil datový typ z int na float a změnil přetypování v admin/model/shipping/zasilkovna_weight_rules.php též z int na float. Data se ukládají již v pořádku, nicméně nevím, zda tato změna nebude dělat problémy někde jinde. 

Pokud není možné tuto změnu udělat globálně, tak prosím o potvrzení, zda bude korektně fungovat má úprava, či co bych měl případně ještě upravit.

Děkuji.

**Comment by packeta-user** [comment]
Dobrý den, 

mohli by jsme váš požadavek příležitostně probrat např. po telefonu?   Upřímně z vašeho popisu nerozumím tomu, jak vám desetiné číslo ve váze pomůže.  Napište nám prosím na technicka.podpora@zasilkovna.cz a předáme si kontakty a domluvíme nějaký termín.

**Comment by packeta-user** [comment]
Bylo přidáno ve verzi 2.0.4

**Comment by dandys71** [comment]
> Bylo přidáno ve verzi 2.0.4

Dobrý den,
moc děkuji a omlouvám se, že jsem se neozval.
