### ISSUE TITLE
Unregistered customer checkout error

### ISSUE THREAD

**Issue by Hourglasser23** [Zasilkovna/opencart3#35]
When I try checkout as an unregistered customer I got this error.
![obrazek](https://user-images.githubusercontent.com/24195289/134156865-6eb1aba3-fe7e-415d-8e90-7c786fabea92.png)

Opencart version 3.0.3.2 and Zasilkovna opencart extension 2.0.4

Works if browser is refreshed and cached address info is already filled.

Also as registered 
![obrazek](https://user-images.githubusercontent.com/24195289/134157098-765e44ac-f4e6-4f0b-84de-3767894a6e46.png)

**Comment by Hourglasser23** [comment]
Also as registered 
![obrazek](https://user-images.githubusercontent.com/24195289/134157098-765e44ac-f4e6-4f0b-84de-3767894a6e46.png)

**Comment by packeta-user** [comment]
This bug has been fixed in version 2.1.0
