### ISSUE TITLE
Modul Zasilkovna OC 3.0.2

### ISSUE THREAD

**Issue by ghost** [Zasilkovna/opencart3#38]
Dobrý den,
zkoušel jsem Vás modul pro Zásilkovnu, Instalace: komprimace souborů do OCMOD.ZIP, načtení do OC3.0.2. Vše se tváří, že OK. Err log=nic:( Napadá Vás, prosím, kde dělám chybu? Děkuji za odpověď
Prima den
Pavel M

**Comment by packeta-user** [comment]
Dobrý den,
když pro instalaci použijete námi připravený instalační soubor ocmod.zip https://github.com/Zasilkovna/opencart3/releases/download/v2.1.0/opencart3-modul-2.1.0.ocmod.zip , tak vám instalace funguje ?
