### ISSUE TITLE
Journal3 Compatibility - nefunknost pluginu

### ISSUE THREAD

**Issue by chcnetconsulting** [Zasilkovna/opencart3#4]
Plugin bohužel neni kompatibilní s temou Journal3, protože shipping se děla ve vue template, a tam není možný pustit dynamicky vygenerován javascriptovy kód. Chtělo by to možnost, jak dostat javascript s widgetem do hlavičky webu. Cili pres $this->document->addScript - jinak se tento kód vůbec nepustí. I kdybychom dali shippingExtension.js do hlavičky s addScriptem, chybí tam stale ještě window.zasilkovnaParemeters, coz je potřeba na fungování shippingExtension.js.

Nejaky napad, jak window.zasilkovnaParemeters dostat do hlavičky pred shippingExtension.js addScript?

Protože jak uz receno pres description, jak to je ted naprogovano, se nedá.

C.

**Comment by packeta-user** [comment]
Dobrý den,  ano, je to přesně tak jak uvádíte.  Současná verze modulu opravdu není kompatibilní s Journal 3. Na podpoře Journal 3 již pracujeme.

**Comment by chcnetconsulting** [comment]
> Dobrý den, ano, je to přesně tak jak uvádíte. Současná verze modulu opravdu není kompatibilní s Journal 3. Na podpoře Journal 3 již pracujeme.

Uz mate něco?

**Comment by canalprivacy** [comment]
> Uz mate něco?

My jsme si upravili sami, v případě zájmu napište na info@canalmedia.eu

**Comment by zemekoule** [comment]
> > Uz mate něco?
> 
> My jsme si upravili sami, v případě zájmu napište na [info@canalmedia.eu](mailto:info@canalmedia.eu)

Novou verzi s podporou Journal 3 vydáme v Lednu.  Nyní provádíme testování modulu.

**Comment by panosnet** [comment]
Dobrý den
Uz mate něco?

**Comment by packeta-user** [comment]
Podpora Journal 3 byla přidána ve verzi 2.0.4
