### ISSUE TITLE
Journal3 a neuložení dodací metody

### ISSUE THREAD

**Issue by Bary** [Zasilkovna/opencart3#41]
Dobrý den,

pokud v journal3 (nezkoušel jsem klasický Xkrokový košík) nejprve zvolím rádio dopravy zásilkovny a poté vyberu pobočku, pak se v sekci nákupního košíku změní doprava na Zásilkovnu a takto se i uloží u objednávky. Pokud nicméně nejprve vyberu pobočku zásilkovny, tak systém sám překlikne rádiobutton dodací metody na zásilkovnu (potud OK), ale už neaktualizuje sekci nákupního košíku a po odeslání zůstává u objednávky předešlá zvolené dodací metoda. Oproti ručnímu zvolení dopravní metody se neprovolává po zvolení pobočky zásilkovny index.php?route=journal3/checkout/save?

**Comment by Bary** [comment]
HOTFIX minimálně pro journal3 theme (do úpravy): zakomentovat https://github.com/Zasilkovna/opencart3/blob/master/upload/catalog/view/javascript/zasilkovna/shippingExtension.js#L183 aby se automaticky neměnila doprava a po výběru výdejního místa (pobočky zásilkovny) byl nucen zákazník překliknout sám.

**Comment by MatyasKoval** [comment]
Dobrý den,
velice děkujeme za nahlášení tohoto chování. Na naší straně se nám ho povedlo replikovat a předali jsme ho k řešení kolegům z vývoje modulů. Opravu vydáme v jedné z budoucích verzí našeho modulu.

S přáním krásného dne,
Matyáš Kovaľ

**Comment by Bary** [comment]
Rozumim tomu spravne, ze ted se ceka na vyrobeni nove release verze, jinak je potreba stahnout master vetev aby zafungovalo..tak?
