### ISSUE TITLE
Novy import version 6

### ISSUE THREAD

**Issue by KeymakerSVK** [Zasilkovna/opencart3#48]
Dobry den. chcel by som sa opytat, ci by ste vedeli pomoct s novym importom do packety. Version 5 uz nieje podporovany. Podla dokumentacie je Version 6. Neviem si ani urobit vlastny importny vzor s tym csv, ktory modul vytvara.

**Comment by MatyasKoval** [comment]
Dobrý den @KeymakerSVK , 
velmi děkuji za Vámi nahlášené chování.
Toto ale není záležitostí přímo našeho modulu, ale Zásilkovny jako takové. Prosím ohledně tohoto chování napište na technicka.podpora@zasilkovna.cz  - modul používá verzi 5, která je nadále podporovaná. Toto chování je způsobeno tím, že Zásilkovně přestal fungovat import zásilek jako takový. Na celém problému se již pracuje. 

Děkuji.
S přáním krásného dne,
Matyáš Kovaľ - E-commerce support
