### ISSUE TITLE
Výdejní místa se nenačítají

### ISSUE THREAD

**Issue by Tomac1** [Zasilkovna/opencart3#5]
Netuším zda-li se na stránce s objednávkou mají načítat výdejní místa či nikoliv, každopádně se nenačítají. 
Verze opencart je 3.0.3.2 + šablona eMarket.

V konzoli vidím "Uncaught ReferenceError: zasilkovnaInitAll is not defined at <anonymous>:1:1".

**Comment by zemekoule** [comment]
Modul připraven pro výchozí košík OpenCartu.  Pokud má Vaše šablona jiné rozvržení prvků, je potřeba modul pro tuto šablonu upravit.  U Ajaxových šablon to bude bohužel poměrně složité, současná verze modulu ajaxové šablony bohužel zatím nepodporuje.  Napište nám prosím na technicka.podpora@zasilkovna.cz  a můžeme se na tuto šablonu blíže podívat a zvážit podporu této šablony v další verzi modulu.
