### ISSUE TITLE
Nefunguje po instalacii na OC 3.0.3.1

### ISSUE THREAD

**Issue by rdrobny** [Zasilkovna/opencart3#6]
![Snímka obrazovky 2020-12-19 o 15 31 39](https://user-images.githubusercontent.com/76255803/102692172-feb3b700-4211-11eb-9404-2ab2f43b23c0.png)

**Comment by dandys71** [comment]
Zdravím, tento problém zřejmě nesouvisí s modulem a ani s verzí Opencartu. Je totiž potřeba aktualizovat verzi PHP na Vašem hostingu - alespoň na verzi 7.0 či vyšší.

V readme je tím pádem chybně uvedeno, že je podporováno PHP ve verzi 5.6 - 7. Využitím funkce dirname() se dvěma parametry se stává modul, pro verze starší než 7.0, nefunkční.

**Comment by packeta-user** [comment]
Dobrý den, tento problém byl již opraven a nejnovější verze modulu https://github.com/Zasilkovna/opencart3/releases/tag/v2.0.4 je plně kompatibilní s PHP 5.6

**Comment by rdrobny** [comment]
Dobrý deň,

veľmi pekne ďakujem!

Drobný Rado

ut 3. 8. 2021 o 8:14 packeta ***@***.***> napísal(a):
