### ISSUE TITLE
AJAX Quick Checkout - jak zprovoznit ukládání do db?

### ISSUE THREAD

**Issue by MichalRuzicka01** [Zasilkovna/opencart3#8]
Dobrý den, při použití modulu AJAX Quick Checkout 6.6.2 pro opencart 3.0.2.0 se neukládá pobočka do databáze.
Jak zprovoznit? Jakou funkci zavolat, aby došlo k uložení?
Prozatím to řeším přidáním id pobočky do komentáře objednávky úpravou viz:
function zasilkovnaSaveSelectedBranch() {
	var branchId = $('#packeta-branch-id').val(),
		dataToSend;
    
    **$("#confirm_comment").html(branchId);
    $("#confirm_comment").change();**
 
 Děkuji

**Comment by packeta-user** [comment]
Dobrý den,   náš modul ajaxové košíky v současné době bohužel nepodporuje.  V současné verzi modulu nemám žádnou jednoduchou radu, jak to zprovoznit.

**Comment by packeta-user** [comment]
Přidání podpory pro AJAX Quick Checkout modul budeme řešit v rámci isuue #23
